name: CI, BUILD, DOCS

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  core:
    name: Core Engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python Linting Tools
        run: pip install black
      
      - name: Install & Build
        run: |
          npm ci
          npm run build
        env:
          DATABASE_URL: "file:./dev.db"
          GEMINI_API_KEY: "dummy"
          NEXT_PUBLIC_API_URL: "http://localhost:4000"
      
      - name: Lint Codebase
        run: npm run lint

      - name: Documentation Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: '.github/linters/mlc_config.json'
